# docker-compose config for ru-web project
# useful commands:
#   docker-compose up -d
#   docker-compose down
#   docker ps
#   docker exec -it ru-web sh
# web-site url: http://localhost:5002/
version: '3'

services:

  ru-web:
    container_name: ru-web
    image: node:10.15.0-alpine
    command: npm run docker-start
    working_dir: /home/app
    volumes:
      - .:/home/app/
    ports:
      - "5002:5000"
    depends_on:
      - ru-postgres
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:rupasswd@ru-postgres/ruweb

  ru-postgres:
    container_name: ru-postgres
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
       - ./var/pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ruweb
      POSTGRES_PASSWORD: rupasswd
      PGDATA: /var/lib/postgresql/data
